### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by zufi110** [thebigpotatoe/Super-Simple-RGB-WiFi-Lamp#2]
Hi
Thanks for this sketch. I want to make this project. during compilation I am having error
"'hMDNSService' in 'class MDNSResponder' does not name a type". I only entered my wifi network / password and number of leds. what I am doing wrong. any help please.
Thanks

**Comment by thebigpotatoe** [comment]
This I hope should be easy. I think it's because you are not running the latest version of the ESP8266 core in the Arduino environment. Just make sure to go to the "tools->boards->boards manager" and update the core from there. Let me know how you go.

**Comment by zufi110** [comment]
Thanks for your reply. I have updated core to latest version. Also removed multiple libraries from a different folder. compiled and uploaded again. Working satisfactory now. Thanks a lot.

**Comment by thebigpotatoe** [comment]
Great, glad it worked. 

If you came here from Instructables. If you enjoy the code and made a light project based on this, it would be great if you could share a simple pic over there :).
