### ISSUE TITLE
Webpage not loading format or responding to light strip interaction

### ISSUE THREAD

**Issue by Megastrik3** [thebigpotatoe/Super-Simple-RGB-WiFi-Lamp#41]
When I boot up the ESP8266 I can connect to the wifi network and open the web page, however, the page appears only as text and small buttons. No color, just a white background and black text. Also, nothing happens when I interact with the buttons in order to control the lights. Any ideas on what the problem could be? (I am using Chrome on a laptop running the latest version of windows)

Thank you.

**Comment by thebigpotatoe** [comment]
Sounds like in general the web page is not loading the dependencies correctly.

If you have not rolled back to the ESP core 2.5.2, this is a current issue discussed over at #26.

If you are using the ESP as an access point the web page will not work unless you have cached the page first as it requires Bootstrap and Jquery to work properly. This is an issue with the implementation of this code, as we cannot store and send the data required to make it work from the access point mode.

If it is another issue this may be another bug. Let me know.

**Comment by Megastrik3** [comment]
Okay, I will give that a try. (Please excuse my ignorance, this is my first arduino base project) I also have a question about the port to use for the board. When I select any port (COM3, COM4) other than COM5 the uploading process always returns an error after/during the connecting process. Is that the correct port to use or have I done something wrong to cause this? Thank you so much for your help!

**Comment by Megastrik3** [comment]
Actually, I got it to work. I honestly have no idea how, but it works!

**Comment by thebigpotatoe** [comment]
> Please excuse my ignorance, this is my first Arduino base project

Any and all contributions are welcome. This is a valid issue, and by the sounds of it you managed to solve it. For . Same goes for most repo's.

This is also an issues tracker, and like other repo's on GitHib, they are managed to report issues and track feature requests with the code contained in a project and how it runs on its platform. Your new issue #42 is a fantastic issue to raise as it relates directly to this code. Many thanks.

Standard issues such as the com port issues you mention above are not related to this repo as it is just a generic Arduino IDE error. There is a fair amount of grey area when deciding if an issue is valid for a repo, but for future, have a read through the existing issues that have been raised and you might find your problem explained there. Just a little something to keep in mind when raising issues across GitHub.

For the com port however, as far as I understand these are generated by your computer for different connected devices. So I have com3 as my keyboard and mouse and com16 is the one my ESP pops up on. It also can change between boards. The com number means nothing, but when you find the one that works, it means you found your board.
