### ISSUE TITLE
OTA not working most of the time

### ISSUE THREAD

**Issue by StefaanVanDooren** [thebigpotatoe/Super-Simple-RGB-WiFi-Lamp#7]
**Describe the bug**
When I made a new bin file in Arduino (Sketch -> export Compiled binary), go the the lamp update page, select the bin file and then update, 8 times out of 10 I get an error page back (ERR_EMPTY_RESPONSE)

Am I doing something wrong, or is there a problem with the OTA ?

**Comment by underwoodblog** [comment]
What Browser are you using?

**Comment by StefaanVanDooren** [comment]
I'm using Chrome, both normal and in incognito.

**Comment by thebigpotatoe** [comment]
From a quick read, seems like google chrome has a few issues which may lead to this error. I use chrome as well for all my uploads and haven't run into this error before so maybe try some of the suggestions from [here](https://blog.pcrisk.com/windows/12807-err-empty-response).

If they don't work it may be an issue, and I can look into it.

**Comment by StefaanVanDooren** [comment]
Based on your previous answer, I tried it with safari, and that seems to be working fine.

**Comment by thebigpotatoe** [comment]
Awesome. Can include this issue then?

**Comment by StefaanVanDooren** [comment]
This issue can be closed.
